Add a missing STL algorithm include
Under CentOS 7.4 / devtoolset-6 compilation used to fail with:

```
error: no matching function for call to ‘max(<brace-enclosed initializer list>)
```