[Usd] Clean up schemaGen error message.
Scenario: An unknown type is specified on an attribute
in a schema. For example

```
\#usda 1.0
(
   subLayers = [
      @usd/schema.usda@
   ]
)

over "GLOBAL" (
   customData = {
        string libraryName = "contrived"
        string libraryPath = "."
        string libraryPrefix = "c"
        string tokensPrefix = "ctrvd"
   }
){
}

class "something" (
   doc = "...."
   inherits = </Typed>
)
{
   uniform boool b = false (doc = "")
}
```

The error before this change:
```
ERROR: <pxr.Sdf.ValueTypeNames object at 0xdeadbeef>
```

The error after this change:
```
ERROR: Code generation requires that all attributes have a known
type (</something.b> has type 'boool', which is not a member of Sdf.ValueTypeNames.)
```

[Usd] Refactor error message so it can be reused.

This gives more consistent errors to the users.

[Usd] Emit for non conforming API Schemas.

Previously, the error message wasnt being reached, instead,
an API schema missing the inherit to APISchemaBase would get

ERROR: 'ClassInfo' object has no attribute 'parentCppClassName'

Now the proper error message(which already existed!) is being hit.