sdf: Workaround for libc++ issue with tuples
The tuple swap in SdfPredicateExpression::FnArg caused
build errors on the macOS Azure Pipelines build like:

   /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/type_traits:3313:71:
error: exception specification of 'operator=<std::__tuple_leaf<1, pxrInternal_v0_23__pxrReserved__::VtValue &, false>>' uses itself
     : public integral_constant<bool, __is_nothrow_assignable(_Tp, _Arg)> {};

   /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/tuple:270:44:
note: in instantiation of template class 'std::__is_nothrow_swappable<std::__tuple_leaf<1, pxrInternal_v0_23__pxrReserved__::VtValue &, false>>' requested here
     int swap(__tuple_leaf& __t) _NOEXCEPT_(__is_nothrow_swappable<__tuple_leaf>::value)

Replacing this with swap calls to each member individually
avoids this problem.

This appears to be an issue in the version of libc++ included in macOS
SDK 12.1, which is included with Xcode 13.2. The libc++ version
included in SDK 12.3 (shipped with Xcode 13.3) does not have this
problem, possibly due to this change:

https://github.com/llvm/llvm-project/commit/a0839b14df6de99fe29bee7cdfff182d50de665d

So this fix isn't required going forward, but it's a small tweak that
allows us to maintain compatibility with previous Xcode versions.

(Internal change: 2291801)