[usdUtils] further fix for testUsdUtilsTimeCodeRange to avoid compilation errors with older versions of clang
Older versions of clang were generating incorrectly optimized code and
different versions were failing at different points in the compilation.

Apple's clang 9.0.0 would issue an error like this:

fatal error: error in backend: unsupported relocation of undefined symbol 'LBB0_-1'

While clang 6.0.1 on linux would issue an error like this:

fatal error: error in backend: Undefined temporary symbol

This change avoids some of these problematic optimizations by removing the
_AssertIsDefaultRange() helper function (preventing the compiler from
trying to inline it), re-using the same 'badRange' variable instead of
using scoping to reset its value, and simply testing whether badRange is
in itself valid instead of comparing it defaultRange.

(Internal change: 1950357)