Some refactoring and updates to the existing TfType parametered IsA/HasAPI and Apply/CanApply/RemoveAPI functions on UsdPrim in preparation for the adding of overloads that take a schema indentifier or a family and version. - All these functions now ask the UsdSchemaRegistry for a SchemaInfo   structure. - The runtime type validation and coding errors in the non-templated   IsA/HasAPI functions have been removed. These just return false   without error if a valid SchemaInfo for the type can't be found. - All the templated functions now just call the non-templated public   functions instead of the private functions.
HasAPI(schemaType, instanceName=TfToken()) has been split into two
explicit overloads HasAPI(schemaType) and
HasAPI(schemaType, instanceName) where the former works for both single
and mulitple apply API schemas while the latter only works for mulitple
apply API schemas. The behavior for callers is identical with one
exception: calling HasAPI(schemaType, instanceName) with an explicitly
empty instanceName is now a coding error whereas previously it was
equivalent to calling HasAPI(schemaType).

Added a type alias and schemaKind to the plugInfo for both UsdSchemaBase
and UsdTyped which are now required due to the use of FindSchema in
UsdPrim::IsA.

(Internal change: 2256583)