APPLE: Move HgiShaderProgramDesc operator== to header
pxr/imaging/hgi/shaderProgram.h contains:
```
HGI_API
inline bool operator==(
    const HgiShaderProgramDesc& lhs,
    const HgiShaderProgramDesc& rhs);
```

But, the definition is only in the .cpp file, so calling it results in a linker error:
```
Undefined symbols for architecture arm64:
  "pxrInternal_v0_25_5__pxrReserved__::operator==(pxrInternal_v0_25_5__pxrReserved__::HgiShaderProgramDesc const&, pxrInternal_v0_25_5__pxrReserved__::HgiShaderProgramDesc const&)", referenced from:
      reproducer(pxrInternal_v0_25_5__pxrReserved__::HgiShaderProgramDesc const&, pxrInternal_v0_25_5__pxrReserved__::HgiShaderProgramDesc const&) in main-d9ce5a.o
ld: symbol(s) not found for architecture arm64
```

Clang also emits this warning:
```
/opt/local/OpenUSD_no-python/include/pxr/imaging/hgi/shaderProgram.h:44:13: warning: inline function 'pxrInternal_v0_25_5__pxrReserved__::operator==' is not defined [-Wundefined-inline]
   44 | inline bool operator==(
      |             ^
main.cpp:44:16: note: used here
   44 |     bool x = l == r;
      |                ^
```

I think the `inline` keyword should be removed from the function declaration, or the function definition should be moved into the header file. (Note that the fix should also be applied to `operator!=`.)